version: "3.7"

services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
      - ./docker/configs/nginx/conf.d/:/etc/nginx/conf.d/
    links:
      - php-fpm
    depends_on:
      - php-fpm
    networks:
      - richinme-network

  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    volumes:
      - ./:/var/www/html
    networks:
      - richinme-network

  postgres:
    build:
      context: ./docker/postgres
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
    networks:
      - richinme-network

networks:
  richinme-network:
    driver: bridge

volumes:
  postgres:
    driver: local