version: "3.7"

services:
  nginx:
    container_name: richinme_nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
      - ./docker/configs/nginx/conf.d/:/etc/nginx/conf.d/
    links:
      - php-fpm
    depends_on:
      - php-fpm
    networks:
      - richinme-network

  php-fpm:
    container_name: richinme_php
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    ports:
    - 9011:9001
    - 9012:9002
    volumes:
      - ./:/var/www/html
    networks:
      - richinme-network

  postgres:
    container_name: richinme_postgres
    build:
      context: ./docker/postgres
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
    networks:
      - richinme-network
    restart: always

  redis:
    container_name: richinme_redis
    hostname: richinme_redis
    image: redis:6.2.2-alpine
    restart: always
    ports:
      - "6377:6377"

networks:
  richinme-network:
    driver: bridge

volumes:
  postgres:
    driver: local