CREATE TABLE public.country
(
    id smallint PRIMARY KEY NOT NULL,
    name varchar(64) NOT NULL,
    shortname varchar(2) NOT NULL
);
CREATE UNIQUE INDEX shortname ON public.country (shortname);
INSERT INTO public.country (id, name, shortname) VALUES (1, 'Afghanistan', 'AF');
INSERT INTO public.country (id, name, shortname) VALUES (2, 'Albania', 'AL');
INSERT INTO public.country (id, name, shortname) VALUES (3, 'Algeria', 'DZ');
INSERT INTO public.country (id, name, shortname) VALUES (4, 'American Samoa', 'AS');
INSERT INTO public.country (id, name, shortname) VALUES (5, 'Andorra', 'AD');
INSERT INTO public.country (id, name, shortname) VALUES (6, 'Angola', 'AO');
INSERT INTO public.country (id, name, shortname) VALUES (7, 'Anguilla', 'AI');
INSERT INTO public.country (id, name, shortname) VALUES (9, 'Antigua and Barbuda', 'AG');
INSERT INTO public.country (id, name, shortname) VALUES (10, 'Argentina', 'AR');
INSERT INTO public.country (id, name, shortname) VALUES (11, 'Armenia', 'AM');
INSERT INTO public.country (id, name, shortname) VALUES (12, 'Aruba', 'AW');
INSERT INTO public.country (id, name, shortname) VALUES (13, 'Australia', 'AU');
INSERT INTO public.country (id, name, shortname) VALUES (14, 'Austria', 'AT');
INSERT INTO public.country (id, name, shortname) VALUES (15, 'Azerbaijan', 'AZ');
INSERT INTO public.country (id, name, shortname) VALUES (16, 'Bahamas', 'BS');
INSERT INTO public.country (id, name, shortname) VALUES (17, 'Bahrain', 'BH');
INSERT INTO public.country (id, name, shortname) VALUES (18, 'Bangladesh', 'BD');
INSERT INTO public.country (id, name, shortname) VALUES (19, 'Barbados', 'BB');
INSERT INTO public.country (id, name, shortname) VALUES (20, 'Belarus', 'BY');
INSERT INTO public.country (id, name, shortname) VALUES (21, 'Belgium', 'BE');
INSERT INTO public.country (id, name, shortname) VALUES (22, 'Belize', 'BZ');
INSERT INTO public.country (id, name, shortname) VALUES (23, 'Benin', 'BJ');
INSERT INTO public.country (id, name, shortname) VALUES (24, 'Bermuda', 'BM');
INSERT INTO public.country (id, name, shortname) VALUES (25, 'Bhutan', 'BT');
INSERT INTO public.country (id, name, shortname) VALUES (26, 'Bolivia', 'BO');
INSERT INTO public.country (id, name, shortname) VALUES (27, 'Bosnia and Herzegovina', 'BA');
INSERT INTO public.country (id, name, shortname) VALUES (28, 'Botswana', 'BW');
INSERT INTO public.country (id, name, shortname) VALUES (30, 'Brazil', 'BR');
INSERT INTO public.country (id, name, shortname) VALUES (33, 'British Virgin Islands', 'VG');
INSERT INTO public.country (id, name, shortname) VALUES (34, 'Brunei', 'BN');
INSERT INTO public.country (id, name, shortname) VALUES (35, 'Bulgaria', 'BG');
INSERT INTO public.country (id, name, shortname) VALUES (36, 'Burkina Faso', 'BF');
INSERT INTO public.country (id, name, shortname) VALUES (37, 'Burundi', 'BI');
INSERT INTO public.country (id, name, shortname) VALUES (38, 'Cambodia', 'KH');
INSERT INTO public.country (id, name, shortname) VALUES (39, 'Cameroon', 'CM');
INSERT INTO public.country (id, name, shortname) VALUES (40, 'Canada', 'CA');
INSERT INTO public.country (id, name, shortname) VALUES (42, 'Cape Verde', 'CV');
INSERT INTO public.country (id, name, shortname) VALUES (43, 'Cayman Islands', 'KY');
INSERT INTO public.country (id, name, shortname) VALUES (44, 'Central African Republic', 'CF');
INSERT INTO public.country (id, name, shortname) VALUES (45, 'Chad', 'TD');
INSERT INTO public.country (id, name, shortname) VALUES (46, 'Chile', 'CL');
INSERT INTO public.country (id, name, shortname) VALUES (47, 'China', 'CN');
INSERT INTO public.country (id, name, shortname) VALUES (50, 'Colombia', 'CO');
INSERT INTO public.country (id, name, shortname) VALUES (51, 'Comoros', 'KM');
INSERT INTO public.country (id, name, shortname) VALUES (52, 'Congo - Brazzaville', 'CG');
INSERT INTO public.country (id, name, shortname) VALUES (53, 'Congo - Kinshasa', 'CD');
INSERT INTO public.country (id, name, shortname) VALUES (54, 'Cook Islands', 'CK');
INSERT INTO public.country (id, name, shortname) VALUES (55, 'Costa Rica', 'CR');
INSERT INTO public.country (id, name, shortname) VALUES (56, 'Croatia', 'HR');
INSERT INTO public.country (id, name, shortname) VALUES (57, 'Cuba', 'CU');
INSERT INTO public.country (id, name, shortname) VALUES (58, 'Cyprus', 'CY');
INSERT INTO public.country (id, name, shortname) VALUES (59, 'Czech Republic', 'CZ');
INSERT INTO public.country (id, name, shortname) VALUES (60, 'Côte d’Ivoire', 'CI');
INSERT INTO public.country (id, name, shortname) VALUES (61, 'Denmark', 'DK');
INSERT INTO public.country (id, name, shortname) VALUES (62, 'Djibouti', 'DJ');
INSERT INTO public.country (id, name, shortname) VALUES (63, 'Dominica', 'DM');
INSERT INTO public.country (id, name, shortname) VALUES (64, 'Dominican Republic', 'DO');
INSERT INTO public.country (id, name, shortname) VALUES (67, 'Ecuador', 'EC');
INSERT INTO public.country (id, name, shortname) VALUES (68, 'Egypt', 'EG');
INSERT INTO public.country (id, name, shortname) VALUES (69, 'El Salvador', 'SV');
INSERT INTO public.country (id, name, shortname) VALUES (70, 'Equatorial Guinea', 'GQ');
INSERT INTO public.country (id, name, shortname) VALUES (71, 'Eritrea', 'ER');
INSERT INTO public.country (id, name, shortname) VALUES (72, 'Estonia', 'EE');
INSERT INTO public.country (id, name, shortname) VALUES (73, 'Ethiopia', 'ET');
INSERT INTO public.country (id, name, shortname) VALUES (75, 'Faroe Islands', 'FO');
INSERT INTO public.country (id, name, shortname) VALUES (76, 'Fiji', 'FJ');
INSERT INTO public.country (id, name, shortname) VALUES (77, 'Finland', 'FI');
INSERT INTO public.country (id, name, shortname) VALUES (78, 'France', 'FR');
INSERT INTO public.country (id, name, shortname) VALUES (80, 'French Polynesia', 'PF');
INSERT INTO public.country (id, name, shortname) VALUES (83, 'Gabon', 'GA');
INSERT INTO public.country (id, name, shortname) VALUES (84, 'Gambia', 'GM');
INSERT INTO public.country (id, name, shortname) VALUES (85, 'Georgia', 'GE');
INSERT INTO public.country (id, name, shortname) VALUES (86, 'Germany', 'DE');
INSERT INTO public.country (id, name, shortname) VALUES (87, 'Ghana', 'GH');
INSERT INTO public.country (id, name, shortname) VALUES (88, 'Gibraltar', 'GI');
INSERT INTO public.country (id, name, shortname) VALUES (89, 'Greece', 'GR');
INSERT INTO public.country (id, name, shortname) VALUES (90, 'Greenland', 'GL');
INSERT INTO public.country (id, name, shortname) VALUES (91, 'Grenada', 'GD');
INSERT INTO public.country (id, name, shortname) VALUES (92, 'Guadeloupe', 'GP');
INSERT INTO public.country (id, name, shortname) VALUES (93, 'Guam', 'GU');
INSERT INTO public.country (id, name, shortname) VALUES (94, 'Guatemala', 'GT');
INSERT INTO public.country (id, name, shortname) VALUES (95, 'Guernsey', 'GG');
INSERT INTO public.country (id, name, shortname) VALUES (96, 'Guinea', 'GN');
INSERT INTO public.country (id, name, shortname) VALUES (97, 'Guinea-Bissau', 'GW');
INSERT INTO public.country (id, name, shortname) VALUES (98, 'Guyana', 'GY');
INSERT INTO public.country (id, name, shortname) VALUES (99, 'Haiti', 'HT');
INSERT INTO public.country (id, name, shortname) VALUES (101, 'Honduras', 'HN');
INSERT INTO public.country (id, name, shortname) VALUES (102, 'Hong Kong SAR China', 'HK');
INSERT INTO public.country (id, name, shortname) VALUES (103, 'Hungary', 'HU');
INSERT INTO public.country (id, name, shortname) VALUES (104, 'Iceland', 'IS');
INSERT INTO public.country (id, name, shortname) VALUES (105, 'India', 'IN');
INSERT INTO public.country (id, name, shortname) VALUES (106, 'Indonesia', 'ID');
INSERT INTO public.country (id, name, shortname) VALUES (107, 'Iran', 'IR');
INSERT INTO public.country (id, name, shortname) VALUES (108, 'Iraq', 'IQ');
INSERT INTO public.country (id, name, shortname) VALUES (109, 'Ireland', 'IE');
INSERT INTO public.country (id, name, shortname) VALUES (110, 'Isle of Man', 'IM');
INSERT INTO public.country (id, name, shortname) VALUES (111, 'Israel', 'IL');
INSERT INTO public.country (id, name, shortname) VALUES (112, 'Italy', 'IT');
INSERT INTO public.country (id, name, shortname) VALUES (113, 'Jamaica', 'JM');
INSERT INTO public.country (id, name, shortname) VALUES (114, 'Japan', 'JP');
INSERT INTO public.country (id, name, shortname) VALUES (115, 'Jersey', 'JE');
INSERT INTO public.country (id, name, shortname) VALUES (117, 'Jordan', 'JO');
INSERT INTO public.country (id, name, shortname) VALUES (118, 'Kazakhstan', 'KZ');
INSERT INTO public.country (id, name, shortname) VALUES (119, 'Kenya', 'KE');
INSERT INTO public.country (id, name, shortname) VALUES (120, 'Kiribati', 'KI');
INSERT INTO public.country (id, name, shortname) VALUES (121, 'Kuwait', 'KW');
INSERT INTO public.country (id, name, shortname) VALUES (122, 'Kyrgyzstan', 'KG');
INSERT INTO public.country (id, name, shortname) VALUES (123, 'Laos', 'LA');
INSERT INTO public.country (id, name, shortname) VALUES (124, 'Latvia', 'LV');
INSERT INTO public.country (id, name, shortname) VALUES (125, 'Lebanon', 'LB');
INSERT INTO public.country (id, name, shortname) VALUES (126, 'Lesotho', 'LS');
INSERT INTO public.country (id, name, shortname) VALUES (127, 'Liberia', 'LR');
INSERT INTO public.country (id, name, shortname) VALUES (128, 'Libya', 'LY');
INSERT INTO public.country (id, name, shortname) VALUES (129, 'Liechtenstein', 'LI');
INSERT INTO public.country (id, name, shortname) VALUES (130, 'Lithuania', 'LT');
INSERT INTO public.country (id, name, shortname) VALUES (131, 'Luxembourg', 'LU');
INSERT INTO public.country (id, name, shortname) VALUES (132, 'Macau SAR China', 'MO');
INSERT INTO public.country (id, name, shortname) VALUES (133, 'Macedonia', 'MK');
INSERT INTO public.country (id, name, shortname) VALUES (134, 'Madagascar', 'MG');
INSERT INTO public.country (id, name, shortname) VALUES (135, 'Malawi', 'MW');
INSERT INTO public.country (id, name, shortname) VALUES (136, 'Malaysia', 'MY');
INSERT INTO public.country (id, name, shortname) VALUES (137, 'Maldives', 'MV');
INSERT INTO public.country (id, name, shortname) VALUES (138, 'Mali', 'ML');
INSERT INTO public.country (id, name, shortname) VALUES (139, 'Malta', 'MT');
INSERT INTO public.country (id, name, shortname) VALUES (140, 'Marshall Islands', 'MH');
INSERT INTO public.country (id, name, shortname) VALUES (141, 'Martinique', 'MQ');
INSERT INTO public.country (id, name, shortname) VALUES (142, 'Mauritania', 'MR');
INSERT INTO public.country (id, name, shortname) VALUES (143, 'Mauritius', 'MU');
INSERT INTO public.country (id, name, shortname) VALUES (146, 'Mexico', 'MX');
INSERT INTO public.country (id, name, shortname) VALUES (147, 'Micronesia', 'FM');
INSERT INTO public.country (id, name, shortname) VALUES (149, 'Moldova', 'MD');
INSERT INTO public.country (id, name, shortname) VALUES (150, 'Monaco', 'MC');
INSERT INTO public.country (id, name, shortname) VALUES (151, 'Mongolia', 'MN');
INSERT INTO public.country (id, name, shortname) VALUES (153, 'Montserrat', 'MS');
INSERT INTO public.country (id, name, shortname) VALUES (154, 'Morocco', 'MA');
INSERT INTO public.country (id, name, shortname) VALUES (155, 'Mozambique', 'MZ');
INSERT INTO public.country (id, name, shortname) VALUES (156, 'Myanmar [Burma]', 'MM');
INSERT INTO public.country (id, name, shortname) VALUES (157, 'Namibia', 'NA');
INSERT INTO public.country (id, name, shortname) VALUES (158, 'Nauru', 'NR');
INSERT INTO public.country (id, name, shortname) VALUES (159, 'Nepal', 'NP');
INSERT INTO public.country (id, name, shortname) VALUES (160, 'Netherlands', 'NL');
INSERT INTO public.country (id, name, shortname) VALUES (161, 'Netherlands Antilles', 'AN');
INSERT INTO public.country (id, name, shortname) VALUES (163, 'New Caledonia', 'NC');
INSERT INTO public.country (id, name, shortname) VALUES (164, 'New Zealand', 'NZ');
INSERT INTO public.country (id, name, shortname) VALUES (165, 'Nicaragua', 'NI');
INSERT INTO public.country (id, name, shortname) VALUES (166, 'Niger', 'NE');
INSERT INTO public.country (id, name, shortname) VALUES (167, 'Nigeria', 'NG');
INSERT INTO public.country (id, name, shortname) VALUES (170, 'North Korea', 'KP');
INSERT INTO public.country (id, name, shortname) VALUES (173, 'Norway', 'NO');
INSERT INTO public.country (id, name, shortname) VALUES (174, 'Oman', 'OM');
INSERT INTO public.country (id, name, shortname) VALUES (176, 'Pakistan', 'PK');
INSERT INTO public.country (id, name, shortname) VALUES (177, 'Palau', 'PW');
INSERT INTO public.country (id, name, shortname) VALUES (178, 'Palestinian Territories', 'PS');
INSERT INTO public.country (id, name, shortname) VALUES (179, 'Panama', 'PA');
INSERT INTO public.country (id, name, shortname) VALUES (181, 'Papua New Guinea', 'PG');
INSERT INTO public.country (id, name, shortname) VALUES (182, 'Paraguay', 'PY');
INSERT INTO public.country (id, name, shortname) VALUES (184, 'Peru', 'PE');
INSERT INTO public.country (id, name, shortname) VALUES (185, 'Philippines', 'PH');
INSERT INTO public.country (id, name, shortname) VALUES (187, 'Poland', 'PL');
INSERT INTO public.country (id, name, shortname) VALUES (188, 'Portugal', 'PT');
INSERT INTO public.country (id, name, shortname) VALUES (189, 'Puerto Rico', 'PR');
INSERT INTO public.country (id, name, shortname) VALUES (190, 'Qatar', 'QA');
INSERT INTO public.country (id, name, shortname) VALUES (191, 'Romania', 'RO');
INSERT INTO public.country (id, name, shortname) VALUES (192, 'Russia', 'RU');
INSERT INTO public.country (id, name, shortname) VALUES (193, 'Rwanda', 'RW');
INSERT INTO public.country (id, name, shortname) VALUES (194, 'Réunion', 'RE');
INSERT INTO public.country (id, name, shortname) VALUES (197, 'Saint Kitts and Nevis', 'KN');
INSERT INTO public.country (id, name, shortname) VALUES (198, 'Saint Lucia', 'LC');
INSERT INTO public.country (id, name, shortname) VALUES (201, 'Saint Vincent and the Grenadines', 'VC');
INSERT INTO public.country (id, name, shortname) VALUES (202, 'Samoa', 'WS');
INSERT INTO public.country (id, name, shortname) VALUES (203, 'San Marino', 'SM');
INSERT INTO public.country (id, name, shortname) VALUES (204, 'Saudi Arabia', 'SA');
INSERT INTO public.country (id, name, shortname) VALUES (205, 'Senegal', 'SN');
INSERT INTO public.country (id, name, shortname) VALUES (206, 'Serbia', 'RS');
INSERT INTO public.country (id, name, shortname) VALUES (207, 'Montenegro', 'CS');
INSERT INTO public.country (id, name, shortname) VALUES (208, 'Seychelles', 'SC');
INSERT INTO public.country (id, name, shortname) VALUES (209, 'Sierra Leone', 'SL');
INSERT INTO public.country (id, name, shortname) VALUES (210, 'Singapore', 'SG');
INSERT INTO public.country (id, name, shortname) VALUES (211, 'Slovakia', 'SK');
INSERT INTO public.country (id, name, shortname) VALUES (212, 'Slovenia', 'SI');
INSERT INTO public.country (id, name, shortname) VALUES (213, 'Solomon Islands', 'SB');
INSERT INTO public.country (id, name, shortname) VALUES (214, 'Somalia', 'SO');
INSERT INTO public.country (id, name, shortname) VALUES (215, 'South Africa', 'ZA');
INSERT INTO public.country (id, name, shortname) VALUES (217, 'South Korea', 'KR');
INSERT INTO public.country (id, name, shortname) VALUES (218, 'Spain', 'ES');
INSERT INTO public.country (id, name, shortname) VALUES (219, 'Sri Lanka', 'LK');
INSERT INTO public.country (id, name, shortname) VALUES (220, 'Sudan', 'SD');
INSERT INTO public.country (id, name, shortname) VALUES (221, 'Suriname', 'SR');
INSERT INTO public.country (id, name, shortname) VALUES (223, 'Swaziland', 'SZ');
INSERT INTO public.country (id, name, shortname) VALUES (224, 'Sweden', 'SE');
INSERT INTO public.country (id, name, shortname) VALUES (225, 'Switzerland', 'CH');
INSERT INTO public.country (id, name, shortname) VALUES (226, 'Syria', 'SY');
INSERT INTO public.country (id, name, shortname) VALUES (227, 'São Tomé and Príncipe', 'ST');
INSERT INTO public.country (id, name, shortname) VALUES (228, 'Taiwan', 'TW');
INSERT INTO public.country (id, name, shortname) VALUES (229, 'Tajikistan', 'TJ');
INSERT INTO public.country (id, name, shortname) VALUES (230, 'Tanzania', 'TZ');
INSERT INTO public.country (id, name, shortname) VALUES (231, 'Thailand', 'TH');
INSERT INTO public.country (id, name, shortname) VALUES (232, 'Timor-Leste', 'TL');
INSERT INTO public.country (id, name, shortname) VALUES (233, 'Togo', 'TG');
INSERT INTO public.country (id, name, shortname) VALUES (235, 'Tonga', 'TO');
INSERT INTO public.country (id, name, shortname) VALUES (236, 'Trinidad and Tobago', 'TT');
INSERT INTO public.country (id, name, shortname) VALUES (237, 'Tunisia', 'TN');
INSERT INTO public.country (id, name, shortname) VALUES (238, 'Turkey', 'TR');
INSERT INTO public.country (id, name, shortname) VALUES (239, 'Turkmenistan', 'TM');
INSERT INTO public.country (id, name, shortname) VALUES (240, 'Turks and Caicos Islands', 'TC');
INSERT INTO public.country (id, name, shortname) VALUES (241, 'Tuvalu', 'TV');
INSERT INTO public.country (id, name, shortname) VALUES (244, 'U.S. Virgin Islands', 'VI');
INSERT INTO public.country (id, name, shortname) VALUES (245, 'Uganda', 'UG');
INSERT INTO public.country (id, name, shortname) VALUES (246, 'Ukraine', 'UA');
INSERT INTO public.country (id, name, shortname) VALUES (248, 'United Arab Emirates', 'AE');
INSERT INTO public.country (id, name, shortname) VALUES (249, 'United Kingdom', 'GB');
INSERT INTO public.country (id, name, shortname) VALUES (250, 'United States', 'US');
INSERT INTO public.country (id, name, shortname) VALUES (252, 'Uruguay', 'UY');
INSERT INTO public.country (id, name, shortname) VALUES (253, 'Uzbekistan', 'UZ');
INSERT INTO public.country (id, name, shortname) VALUES (254, 'Vanuatu', 'VU');
INSERT INTO public.country (id, name, shortname) VALUES (255, 'Vatican City', 'VA');
INSERT INTO public.country (id, name, shortname) VALUES (256, 'Venezuela', 'VE');
INSERT INTO public.country (id, name, shortname) VALUES (257, 'Vietnam', 'VN');
INSERT INTO public.country (id, name, shortname) VALUES (260, 'Western Sahara', 'EH');
INSERT INTO public.country (id, name, shortname) VALUES (261, 'Yemen', 'YE');
INSERT INTO public.country (id, name, shortname) VALUES (262, 'Zambia', 'ZM');
INSERT INTO public.country (id, name, shortname) VALUES (263, 'Zimbabwe', 'ZW');